name: my_portfolio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  #to compare objects
  equatable: ^2.0.5
  # state management
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  #functional programming
  dartz: ^0.10.1
  #service loacator
  get_it: ^7.7.0
  # to handle network requests
  dio: ^5.7.0
  internet_connection_checker: 1.0.0+1
  # for SVG images
  flutter_svg: ^2.0.10+1
  #app animation
  flutter_animate: ^4.5.0
  #to handle services locator generating
  injectable: ^2.4.4
  #to get google account id
  firebase_core: ^3.4.1
  #local Data base
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  #to pick & re-size images
  image: ^4.2.0
  image_picker: ^1.1.2
  #for launcher urls in contact us
  url_launcher: ^6.3.0
  #for arabic local ltr
  flutter_localization: ^0.2.2
  #  path_provider_foundation: ^2.3.1
  intl: ^0.20.2
  easy_localization: ^3.0.8
  flutter_phoenix: ^1.1.1
  shared_preferences: ^2.3.2
  youtube_player_iframe: ^5.2.0
  firebase_data_connect: ^0.1.2+1
  connectivity_plus: ^7.0.0
  lottie: ^3.3.0



dev_dependencies:
  flutter_test:
    sdk: flutter



  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  injectable_generator: ^2.6.2
  hive_generator: ^2.0.1

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/translations/


  fonts:

    - family: Playfair_Display
      fonts:
        - asset: assets/fonts/Playfair_Display/PlayfairDisplay-Black.ttf
          weight: 900
        - asset: assets/fonts/Playfair_Display/PlayfairDisplay-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Playfair_Display/PlayfairDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/Playfair_Display/PlayfairDisplay-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Playfair_Display/PlayfairDisplay-Italic.ttf
          style: italic
        - asset: assets/fonts/Playfair_Display/PlayfairDisplay-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Playfair_Display/PlayfairDisplay-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Playfair_Display/PlayfairDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/Playfair_Display/PlayfairDisplay-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Playfair_Display/PlayfairDisplay-Regular.ttf
        - asset: assets/fonts/Playfair_Display/PlayfairDisplay-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Playfair_Display/PlayfairDisplay-SemiBoldItalic.ttf
          weight: 600
          style: italic


    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto/Roboto-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 800
        - asset: assets/fonts/Roboto/Roboto-LightItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
          weight: 600
        - asset: assets/fonts/Roboto/Roboto-ThinItalic.ttf
          weight: 600
          style: italic